emacs-install has better download and verify signature handling

diff --git a/emacs-install b/emacs-install
--- a/emacs-install
+++ b/emacs-install
@@ -2,65 +2,102 @@
 
 set -eE
 
-src_dir=~/src
 release=24.3
-build_dir=$src_dir/emacs-${release}
-bundle_file=emacs-${release}.tar.xz
-sig_file=${bundle_file}.sig
-
-file_uri=http://ftp.gnu.org/gnu/emacs/$bundle_file
-
-# always download signature from gnu.org
-sig_uri=http://ftp.gnu.org/gnu/emacs/$sig_file
 
 ################
 
-mkdir -p ~/Downloads
-cd ~/Downloads
+function determine_os_type () {
+    if [ -f /etc/redhat-release ] ; then
+        echo rhel
+    elif [ -f /etc/debian-release ] ; then
+        echo debian
+    elif [ -f /etc/system-release ] ; then
+        echo $(determine_os_type_from_file /etc/system-release)
+    elif [ -f /etc/os-release ] ; then
+        echo $(determine_os_type_from_file /etc/os-release)
+    else
+        echo "ERROR: cannot determine os type. install dependencies manually" >&2
+        exit 1
+    fi
+}
 
-curl -LOC - $sig_uri
-
-if [ ! -f ~/Downloads/$bundle_file ] ; then
-    curl -LOC - $file_uri
-fi
-
-# gpg --keyserver pgpkeys.mit.edu --recv-key A0B0F199
-if ! gpg --verify ~/Downloads/$sig_file ~/Downloads/$bundle_file ; then
-    echo "ERROR: file doesn't match signature" >&2
-    ls -l ~/Downloads/$bundle_file
-    exit 1
-fi
-
-cd ~/src
-# rm -rf $build_dir
-# tar Jxvf ~/Downloads/$bundle_file
-cd $build_dir
+function determine_os_type_from_file () {
+    local file=$1
+    local type
+    read contents <$file
+    case $contents in
+        'Red Hat'*) type=rhel ;;
+        'Debian'*) type=debian ;;
+        *)
+            echo "unknown os type: $contents" >&2
+            exit 1
+    esac
+    echo $type
+}
 
 ################
 # dependencies
 
-if [ -f /etc/os-release ] ; then
-    file=/etc/os-release
-elif [ -f /etc/system-release ] ; then
-    file=/etc/system-release
-else
-    echo "ERROR: cannot determine os type. install dependencies manually" >&2
-    exit 1
-fi
-
-if grep -i -q debian $file ; then
-    sudo apt-get install build-essential
-    sudo apt-get build-dep emacs24
-elif grep -i -q 'Red Hat' $file ; then
-    sudo yum install gtk2 gtk2-devel libXpm-devel giflib-devel libtiff-devel libjpeg libjpeg-devel ncurses ncurses-devel
-else
-    echo "ERROR: cannot determine os type. install dependencies manually" >&2
-    exit 1
-fi
+case $(determine_os_type) in
+    rhel)
+        sudo yum install gtk2 gtk2-devel libXpm-devel giflib-devel libtiff-devel libjpeg libjpeg-devel ncurses ncurses-devel
+        ;;
+    debian)
+        sudo apt-get install build-essential
+        sudo apt-get build-dep emacs24
+        ;;
+    *)
+        echo "ERROR: cannot determine os type. install dependencies manually or fix this script" >&2
+        exit 1
+        ;;
+esac
 
 ################
 
+bundle=emacs-${release}.tar.xz
+sig=${bundle}.sig
+
+bundle_local=~/Downloads/$bundle
+sig_local=~/Downloads/$sig
+
+bundle_uri=http://ftp.gnu.org/gnu/emacs/$bundle
+# always download signature from gnu.org
+sig_uri=http://ftp.gnu.org/gnu/emacs/$sig
+
+################
+
+while ! gpg --verify $sig_local $bundle_local ; do
+    if [ -f $sig_local -a -f $bundle_local ] ; then
+        echo "ERROR: file doesn't match signature?" >&2
+        read -e -p "Remove bundle and signature, and retry? [Y/n] " yn
+        case $yn in
+            Y|y)
+                rm -f $sig_local $bundle_local
+                ;;
+            N|n)
+                echo "exiting because bundle does not match signature..."
+                exit 1
+                ;;
+        esac
+    fi
+    [ -f $sig_local ] || curl -L --create-dirs --output $sig_local $sig_uri
+    [ -f $bundle_local ] || curl -L --create-dirs --output $bundle_local $bundle_uri
+    # gpg --keyserver pgpkeys.mit.edu --recv-key A0B0F199
+done
+
+################
+
+src_dir=~/src
+build_dir=$src_dir/emacs-${release}
+
+rm -rf $build_dir
+tar -Jx -C $src_dir -f $bundle_local
+
+################
+
+cd $build_dir
 ./configure
 make
+
 sudo make install
 sudo alternatives --install /usr/bin/emacs emacs /usr/local/bin/emacs 20000
